/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_defendec_subsserver_MLE */

#ifndef _Included_com_defendec_subsserver_MLE
#define _Included_com_defendec_subsserver_MLE
#ifdef __cplusplus
extern "C" {
#endif
#undef com_defendec_subsserver_MLE_bufferSize
#define com_defendec_subsserver_MLE_bufferSize 255L
/*
 * Class:     com_defendec_subsserver_MLE
 * Method:    create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_defendec_subsserver_MLE_create
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_defendec_subsserver_MLE
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_defendec_subsserver_MLE_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_defendec_subsserver_MLE
 * Method:    MLE_encode
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_defendec_subsserver_MLE_MLE_1getEncoded
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_defendec_subsserver_MLE
 * Method:    MLE_appendObject
 * Signature: (JJ)S
 */
JNIEXPORT jshort JNICALL Java_com_defendec_subsserver_MLE_MLE_1appendObject
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_defendec_subsserver_MLE
 * Method:    MLE_appendOSV
 * Signature: (JJSI)S
 */
JNIEXPORT jshort JNICALL Java_com_defendec_subsserver_MLE_MLE_1appendOSV
  (JNIEnv *, jobject, jlong, jlong, jshort, jint);

/*
 * Class:     com_defendec_subsserver_MLE
 * Method:    MLE_appendOV
 * Signature: (JJI)S
 */
JNIEXPORT jshort JNICALL Java_com_defendec_subsserver_MLE_MLE_1appendOV
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_defendec_subsserver_MLE
 * Method:    MLE_appendOS
 * Signature: (JJS)S
 */
JNIEXPORT jshort JNICALL Java_com_defendec_subsserver_MLE_MLE_1appendOS
  (JNIEnv *, jobject, jlong, jlong, jshort);

/*
 * Class:     com_defendec_subsserver_MLE
 * Method:    MLE_appendO
 * Signature: (JJ)S
 */
JNIEXPORT jshort JNICALL Java_com_defendec_subsserver_MLE_MLE_1appendO
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_defendec_subsserver_MLE
 * Method:    MLE_spaceLeft
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_defendec_subsserver_MLE_MLE_1spaceLeft
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_defendec_subsserver_MLE
 * Method:    MLE_spaceUsed
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_defendec_subsserver_MLE_MLE_1spaceUsed
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_defendec_subsserver_MLE
 * Method:    MLE_deleteObject
 * Signature: (JS)S
 */
JNIEXPORT jshort JNICALL Java_com_defendec_subsserver_MLE_MLE_1deleteObject
  (JNIEnv *, jobject, jlong, jshort);

#ifdef __cplusplus
}
#endif
#endif
