/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_defendec_subsserver_MLI */

#ifndef _Included_com_defendec_subsserver_MLI
#define _Included_com_defendec_subsserver_MLI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_defendec_subsserver_MLI
 * Method:    create
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_defendec_subsserver_MLI_create
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_defendec_subsserver_MLI
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_defendec_subsserver_MLI_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_defendec_subsserver_MLI
 * Method:    MLE_reset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_defendec_subsserver_MLI_MLE_1reset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_defendec_subsserver_MLI
 * Method:    MLE_next
 * Signature: (J)Lcom/defendec/subsserver/MLO;
 */
JNIEXPORT jobject JNICALL Java_com_defendec_subsserver_MLI_MLE_1next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_defendec_subsserver_MLI
 * Method:    MLI_nextWithSubject
 * Signature: (JS)Lcom/defendec/subsserver/MLO;
 */
JNIEXPORT jobject JNICALL Java_com_defendec_subsserver_MLI_MLI_1nextWithSubject
  (JNIEnv *, jobject, jlong, jshort);

#ifdef __cplusplus
}
#endif
#endif
