/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_defendec_subsserver_MLO */

#ifndef _Included_com_defendec_subsserver_MLO
#define _Included_com_defendec_subsserver_MLO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_defendec_subsserver_MLO
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_defendec_subsserver_MLO_create
  (JNIEnv *, jobject);

/*
 * Class:     com_defendec_subsserver_MLO
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_defendec_subsserver_MLO_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_defendec_subsserver_MLO
 * Method:    MLO_getIndex
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_defendec_subsserver_MLO_MLO_1getIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_defendec_subsserver_MLO
 * Method:    MLO_getType
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_defendec_subsserver_MLO_MLO_1getType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_defendec_subsserver_MLO
 * Method:    MLO_getValue
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_defendec_subsserver_MLO_MLO_1getValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_defendec_subsserver_MLO
 * Method:    MLO_getValueIsPresent
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_defendec_subsserver_MLO_MLO_1getValueIsPresent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_defendec_subsserver_MLO
 * Method:    MLO_getSubject
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_defendec_subsserver_MLO_MLO_1getSubject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_defendec_subsserver_MLO
 * Method:    MLO_getBuffer
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_defendec_subsserver_MLO_MLO_1getBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_defendec_subsserver_MLO
 * Method:    MLO_setIndex
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_com_defendec_subsserver_MLO_MLO_1setIndex
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     com_defendec_subsserver_MLO
 * Method:    MLO_setType
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_defendec_subsserver_MLO_MLO_1setType
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_defendec_subsserver_MLO
 * Method:    MLO_setValue
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_defendec_subsserver_MLO_MLO_1setValue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_defendec_subsserver_MLO
 * Method:    MLO_setValueIsPresent
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_defendec_subsserver_MLO_MLO_1setValueIsPresent
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_defendec_subsserver_MLO
 * Method:    MLO_setSubject
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_com_defendec_subsserver_MLO_MLO_1setSubject
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     com_defendec_subsserver_MLO
 * Method:    MLO_setBuffer
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_defendec_subsserver_MLO_MLO_1setBuffer
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
